//go:build !disable_pgv
// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy/extensions/transport_sockets/tls/v3/grpc_certificate_provider.proto

package tlsv3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GrpcCertificateProviderConfig with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GrpcCertificateProviderConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrpcCertificateProviderConfig with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GrpcCertificateProviderConfigMultiError, or nil if none found.
func (m *GrpcCertificateProviderConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *GrpcCertificateProviderConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetGrpcService() == nil {
		err := GrpcCertificateProviderConfigValidationError{
			field:  "GrpcService",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetGrpcService()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GrpcCertificateProviderConfigValidationError{
					field:  "GrpcService",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GrpcCertificateProviderConfigValidationError{
					field:  "GrpcService",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGrpcService()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GrpcCertificateProviderConfigValidationError{
				field:  "GrpcService",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTimeout()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GrpcCertificateProviderConfigValidationError{
					field:  "Timeout",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GrpcCertificateProviderConfigValidationError{
					field:  "Timeout",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimeout()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GrpcCertificateProviderConfigValidationError{
				field:  "Timeout",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCacheTtl()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GrpcCertificateProviderConfigValidationError{
					field:  "CacheTtl",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GrpcCertificateProviderConfigValidationError{
					field:  "CacheTtl",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCacheTtl()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GrpcCertificateProviderConfigValidationError{
				field:  "CacheTtl",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CacheMaxEntries

	// no validation rules for FailOnError

	if len(errors) > 0 {
		return GrpcCertificateProviderConfigMultiError(errors)
	}

	return nil
}

// GrpcCertificateProviderConfigMultiError is an error wrapping multiple
// validation errors returned by GrpcCertificateProviderConfig.ValidateAll()
// if the designated constraints aren't met.
type GrpcCertificateProviderConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrpcCertificateProviderConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrpcCertificateProviderConfigMultiError) AllErrors() []error { return m }

// GrpcCertificateProviderConfigValidationError is the validation error
// returned by GrpcCertificateProviderConfig.Validate if the designated
// constraints aren't met.
type GrpcCertificateProviderConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrpcCertificateProviderConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrpcCertificateProviderConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrpcCertificateProviderConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrpcCertificateProviderConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrpcCertificateProviderConfigValidationError) ErrorName() string {
	return "GrpcCertificateProviderConfigValidationError"
}

// Error satisfies the builtin error interface
func (e GrpcCertificateProviderConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrpcCertificateProviderConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrpcCertificateProviderConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrpcCertificateProviderConfigValidationError{}
