// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: envoy/extensions/transport_sockets/tls/v3/grpc_certificate_provider.proto

package tlsv3

import (
	_ "github.com/cncf/xds/go/udpa/annotations"
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for the gRPC certificate provider handshaker extension.
// This handshaker intercepts the TLS handshake to fetch certificates dynamically
// from an external gRPC service based on the SNI (Server Name Indication) from
// the ClientHello message.
// [#next-free-field: 7]
type GrpcCertificateProviderConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The gRPC service that provides certificates. This service must implement
	// the CertificateProviderService defined in //api/envoy/service/tls/v3.
	// [#comment:TODO(mattward): consider supporting multiple services for failover]
	GrpcService *v3.GrpcService `protobuf:"bytes,1,opt,name=grpc_service,json=grpcService,proto3" json:"grpc_service,omitempty"`
	// Timeout for the gRPC call to fetch certificates. If the timeout is reached,
	// the handshake will fail unless a fallback certificate is configured.
	// Default: 5 seconds.
	Timeout *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Optional cache TTL for certificates. When set, successfully fetched certificates
	// will be cached and reused for subsequent connections with the same SNI.
	// If not set, no caching is performed and every handshake triggers a gRPC call.
	CacheTtl *durationpb.Duration `protobuf:"bytes,3,opt,name=cache_ttl,json=cacheTtl,proto3" json:"cache_ttl,omitempty"`
	// Maximum number of certificates to cache. Only used when cache_ttl is set.
	// Default: 1000.
	CacheMaxEntries uint32 `protobuf:"varint,4,opt,name=cache_max_entries,json=cacheMaxEntries,proto3" json:"cache_max_entries,omitempty"`
	// If true, handshake will fail when the gRPC call fails or times out.
	// If false (default), the handshake will proceed without a certificate,
	// which will likely cause the TLS handshake to fail on the client side.
	FailOnError bool `protobuf:"varint,5,opt,name=fail_on_error,json=failOnError,proto3" json:"fail_on_error,omitempty"`
	// Optional HTTP/2 ":authority" header for the FetchCertificate gRPC call.
	// When set, the client overrides the default authority (derived from
	// grpc_service.google_grpc.target_uri) via
	// “grpc::ClientContext::set_authority()“. Useful when one
	// CertificateProviderService backs multiple Envoy listeners and needs to
	// identify the caller server-side without depending on the peer source IP.
	Authority     string `protobuf:"bytes,6,opt,name=authority,proto3" json:"authority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcCertificateProviderConfig) Reset() {
	*x = GrpcCertificateProviderConfig{}
	mi := &file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcCertificateProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcCertificateProviderConfig) ProtoMessage() {}

func (x *GrpcCertificateProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcCertificateProviderConfig.ProtoReflect.Descriptor instead.
func (*GrpcCertificateProviderConfig) Descriptor() ([]byte, []int) {
	return file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcCertificateProviderConfig) GetGrpcService() *v3.GrpcService {
	if x != nil {
		return x.GrpcService
	}
	return nil
}

func (x *GrpcCertificateProviderConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *GrpcCertificateProviderConfig) GetCacheTtl() *durationpb.Duration {
	if x != nil {
		return x.CacheTtl
	}
	return nil
}

func (x *GrpcCertificateProviderConfig) GetCacheMaxEntries() uint32 {
	if x != nil {
		return x.CacheMaxEntries
	}
	return 0
}

func (x *GrpcCertificateProviderConfig) GetFailOnError() bool {
	if x != nil {
		return x.FailOnError
	}
	return false
}

func (x *GrpcCertificateProviderConfig) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

var File_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto protoreflect.FileDescriptor

const file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_rawDesc = "" +
	"\n" +
	"Ienvoy/extensions/transport_sockets/tls/v3/grpc_certificate_provider.proto\x12)envoy.extensions.transport_sockets.tls.v3\x1a$envoy/config/core/v3/extension.proto\x1a'envoy/config/core/v3/grpc_service.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\xca\x02\n" +
	"\x1dGrpcCertificateProviderConfig\x12N\n" +
	"\fgrpc_service\x18\x01 \x01(\v2!.envoy.config.core.v3.GrpcServiceB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vgrpcService\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x126\n" +
	"\tcache_ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bcacheTtl\x12*\n" +
	"\x11cache_max_entries\x18\x04 \x01(\rR\x0fcacheMaxEntries\x12\"\n" +
	"\rfail_on_error\x18\x05 \x01(\bR\vfailOnError\x12\x1c\n" +
	"\tauthority\x18\x06 \x01(\tR\tauthorityB\xb9\x01\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"7io.envoyproxy.envoy.extensions.transport_sockets.tls.v3B\x1cGrpcCertificateProviderProtoP\x01ZVgithub.com/envoyproxy/go-control-plane/envoy/extensions/transport_sockets/tls/v3;tlsv3b\x06proto3"

var (
	file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_rawDescOnce sync.Once
	file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_rawDescData []byte
)

func file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_rawDescGZIP() []byte {
	file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_rawDescOnce.Do(func() {
		file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_rawDesc), len(file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_rawDesc)))
	})
	return file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_rawDescData
}

var file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_goTypes = []any{
	(*GrpcCertificateProviderConfig)(nil), // 0: envoy.extensions.transport_sockets.tls.v3.GrpcCertificateProviderConfig
	(*v3.GrpcService)(nil),                // 1: envoy.config.core.v3.GrpcService
	(*durationpb.Duration)(nil),           // 2: google.protobuf.Duration
}
var file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_depIdxs = []int32{
	1, // 0: envoy.extensions.transport_sockets.tls.v3.GrpcCertificateProviderConfig.grpc_service:type_name -> envoy.config.core.v3.GrpcService
	2, // 1: envoy.extensions.transport_sockets.tls.v3.GrpcCertificateProviderConfig.timeout:type_name -> google.protobuf.Duration
	2, // 2: envoy.extensions.transport_sockets.tls.v3.GrpcCertificateProviderConfig.cache_ttl:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_init() }
func file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_init() {
	if File_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_rawDesc), len(file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_goTypes,
		DependencyIndexes: file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_depIdxs,
		MessageInfos:      file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_msgTypes,
	}.Build()
	File_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto = out.File
	file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_goTypes = nil
	file_envoy_extensions_transport_sockets_tls_v3_grpc_certificate_provider_proto_depIdxs = nil
}
