// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: envoy/service/tls/v3/grpc_certificate_provider.proto

package tlsv3

import (
	_ "github.com/cncf/xds/go/udpa/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status of the certificate fetch operation.
type CertificateResponse_Status int32

const (
	// Certificate was successfully retrieved.
	CertificateResponse_SUCCESS CertificateResponse_Status = 0
	// No certificate found for the requested SNI.
	CertificateResponse_NOT_FOUND CertificateResponse_Status = 1
	// An error occurred while fetching the certificate.
	CertificateResponse_ERROR CertificateResponse_Status = 2
)

// Enum value maps for CertificateResponse_Status.
var (
	CertificateResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "NOT_FOUND",
		2: "ERROR",
	}
	CertificateResponse_Status_value = map[string]int32{
		"SUCCESS":   0,
		"NOT_FOUND": 1,
		"ERROR":     2,
	}
)

func (x CertificateResponse_Status) Enum() *CertificateResponse_Status {
	p := new(CertificateResponse_Status)
	*p = x
	return p
}

func (x CertificateResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_envoy_service_tls_v3_grpc_certificate_provider_proto_enumTypes[0].Descriptor()
}

func (CertificateResponse_Status) Type() protoreflect.EnumType {
	return &file_envoy_service_tls_v3_grpc_certificate_provider_proto_enumTypes[0]
}

func (x CertificateResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateResponse_Status.Descriptor instead.
func (CertificateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDescGZIP(), []int{1, 0}
}

// Request message sent to the certificate provider service during TLS handshake.
type CertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server Name Indication (SNI) extracted from the TLS ClientHello.
	// This is the primary key used by the certificate provider to select
	// the appropriate certificate.
	Sni string `protobuf:"bytes,1,opt,name=sni,proto3" json:"sni,omitempty"`
	// Client IP address in string format (e.g., "192.168.1.1" or "::1").
	// Useful for geo-based certificate selection or audit logging.
	ClientAddress string `protobuf:"bytes,2,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	// TLS version string (e.g., "TLSv1.2", "TLSv1.3").
	ClientTlsVersion string `protobuf:"bytes,3,opt,name=client_tls_version,json=clientTlsVersion,proto3" json:"client_tls_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CertificateRequest) Reset() {
	*x = CertificateRequest{}
	mi := &file_envoy_service_tls_v3_grpc_certificate_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequest) ProtoMessage() {}

func (x *CertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_service_tls_v3_grpc_certificate_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequest.ProtoReflect.Descriptor instead.
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateRequest) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *CertificateRequest) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

func (x *CertificateRequest) GetClientTlsVersion() string {
	if x != nil {
		return x.ClientTlsVersion
	}
	return ""
}

// Response from the certificate provider service.
// [#next-free-field: 9]
type CertificateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of the certificate fetch.
	Status CertificateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=envoy.service.tls.v3.CertificateResponse_Status" json:"status,omitempty"`
	// PEM-encoded certificate chain. The leaf certificate should be first,
	// followed by any intermediate certificates. The root CA should typically
	// not be included.
	CertificateChainPem string `protobuf:"bytes,2,opt,name=certificate_chain_pem,json=certificateChainPem,proto3" json:"certificate_chain_pem,omitempty"`
	// PEM-encoded private key corresponding to the leaf certificate.
	// This field is sensitive and should be transmitted over a secure channel.
	PrivateKeyPem string `protobuf:"bytes,3,opt,name=private_key_pem,json=privateKeyPem,proto3" json:"private_key_pem,omitempty"`
	// Optional password for encrypted private keys.
	// If the private key is encrypted, this password will be used to decrypt it.
	PrivateKeyPassword string `protobuf:"bytes,4,opt,name=private_key_password,json=privateKeyPassword,proto3" json:"private_key_password,omitempty"`
	// Optional OCSP response for stapling, DER-encoded.
	// If provided and the client supports OCSP stapling, this will be sent
	// during the TLS handshake.
	OcspResponse []byte `protobuf:"bytes,5,opt,name=ocsp_response,json=ocspResponse,proto3" json:"ocsp_response,omitempty"`
	// Optional Signed Certificate Timestamp (SCT) list for Certificate Transparency.
	SignedCertificateTimestamp []byte `protobuf:"bytes,6,opt,name=signed_certificate_timestamp,json=signedCertificateTimestamp,proto3" json:"signed_certificate_timestamp,omitempty"`
	// Suggested cache TTL for this specific certificate.
	// If provided, this overrides the default cache_ttl from the config.
	CacheTtl *durationpb.Duration `protobuf:"bytes,7,opt,name=cache_ttl,json=cacheTtl,proto3" json:"cache_ttl,omitempty"`
	// Error message when status is NOT_FOUND or ERROR.
	// This message is logged but not sent to the client.
	ErrorMessage  string `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateResponse) Reset() {
	*x = CertificateResponse{}
	mi := &file_envoy_service_tls_v3_grpc_certificate_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateResponse) ProtoMessage() {}

func (x *CertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_service_tls_v3_grpc_certificate_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateResponse.ProtoReflect.Descriptor instead.
func (*CertificateResponse) Descriptor() ([]byte, []int) {
	return file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateResponse) GetStatus() CertificateResponse_Status {
	if x != nil {
		return x.Status
	}
	return CertificateResponse_SUCCESS
}

func (x *CertificateResponse) GetCertificateChainPem() string {
	if x != nil {
		return x.CertificateChainPem
	}
	return ""
}

func (x *CertificateResponse) GetPrivateKeyPem() string {
	if x != nil {
		return x.PrivateKeyPem
	}
	return ""
}

func (x *CertificateResponse) GetPrivateKeyPassword() string {
	if x != nil {
		return x.PrivateKeyPassword
	}
	return ""
}

func (x *CertificateResponse) GetOcspResponse() []byte {
	if x != nil {
		return x.OcspResponse
	}
	return nil
}

func (x *CertificateResponse) GetSignedCertificateTimestamp() []byte {
	if x != nil {
		return x.SignedCertificateTimestamp
	}
	return nil
}

func (x *CertificateResponse) GetCacheTtl() *durationpb.Duration {
	if x != nil {
		return x.CacheTtl
	}
	return nil
}

func (x *CertificateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_envoy_service_tls_v3_grpc_certificate_provider_proto protoreflect.FileDescriptor

const file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDesc = "" +
	"\n" +
	"4envoy/service/tls/v3/grpc_certificate_provider.proto\x12\x14envoy.service.tls.v3\x1a\x1egoogle/protobuf/duration.proto\x1a\x1dudpa/annotations/status.proto\"{\n" +
	"\x12CertificateRequest\x12\x10\n" +
	"\x03sni\x18\x01 \x01(\tR\x03sni\x12%\n" +
	"\x0eclient_address\x18\x02 \x01(\tR\rclientAddress\x12,\n" +
	"\x12client_tls_version\x18\x03 \x01(\tR\x10clientTlsVersion\"\xe2\x03\n" +
	"\x13CertificateResponse\x12H\n" +
	"\x06status\x18\x01 \x01(\x0e20.envoy.service.tls.v3.CertificateResponse.StatusR\x06status\x122\n" +
	"\x15certificate_chain_pem\x18\x02 \x01(\tR\x13certificateChainPem\x12&\n" +
	"\x0fprivate_key_pem\x18\x03 \x01(\tR\rprivateKeyPem\x120\n" +
	"\x14private_key_password\x18\x04 \x01(\tR\x12privateKeyPassword\x12#\n" +
	"\rocsp_response\x18\x05 \x01(\fR\focspResponse\x12@\n" +
	"\x1csigned_certificate_timestamp\x18\x06 \x01(\fR\x1asignedCertificateTimestamp\x126\n" +
	"\tcache_ttl\x18\a \x01(\v2\x19.google.protobuf.DurationR\bcacheTtl\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"/\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x022\x87\x01\n" +
	"\x1aCertificateProviderService\x12i\n" +
	"\x10FetchCertificate\x12(.envoy.service.tls.v3.CertificateRequest\x1a).envoy.service.tls.v3.CertificateResponse\"\x00B\x8f\x01\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"\"io.envoyproxy.envoy.service.tls.v3B\x1cGrpcCertificateProviderProtoP\x01ZAgithub.com/envoyproxy/go-control-plane/envoy/service/tls/v3;tlsv3b\x06proto3"

var (
	file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDescOnce sync.Once
	file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDescData []byte
)

func file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDescGZIP() []byte {
	file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDescOnce.Do(func() {
		file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDesc), len(file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDesc)))
	})
	return file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDescData
}

var file_envoy_service_tls_v3_grpc_certificate_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_envoy_service_tls_v3_grpc_certificate_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_envoy_service_tls_v3_grpc_certificate_provider_proto_goTypes = []any{
	(CertificateResponse_Status)(0), // 0: envoy.service.tls.v3.CertificateResponse.Status
	(*CertificateRequest)(nil),      // 1: envoy.service.tls.v3.CertificateRequest
	(*CertificateResponse)(nil),     // 2: envoy.service.tls.v3.CertificateResponse
	(*durationpb.Duration)(nil),     // 3: google.protobuf.Duration
}
var file_envoy_service_tls_v3_grpc_certificate_provider_proto_depIdxs = []int32{
	0, // 0: envoy.service.tls.v3.CertificateResponse.status:type_name -> envoy.service.tls.v3.CertificateResponse.Status
	3, // 1: envoy.service.tls.v3.CertificateResponse.cache_ttl:type_name -> google.protobuf.Duration
	1, // 2: envoy.service.tls.v3.CertificateProviderService.FetchCertificate:input_type -> envoy.service.tls.v3.CertificateRequest
	2, // 3: envoy.service.tls.v3.CertificateProviderService.FetchCertificate:output_type -> envoy.service.tls.v3.CertificateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_envoy_service_tls_v3_grpc_certificate_provider_proto_init() }
func file_envoy_service_tls_v3_grpc_certificate_provider_proto_init() {
	if File_envoy_service_tls_v3_grpc_certificate_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDesc), len(file_envoy_service_tls_v3_grpc_certificate_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_envoy_service_tls_v3_grpc_certificate_provider_proto_goTypes,
		DependencyIndexes: file_envoy_service_tls_v3_grpc_certificate_provider_proto_depIdxs,
		EnumInfos:         file_envoy_service_tls_v3_grpc_certificate_provider_proto_enumTypes,
		MessageInfos:      file_envoy_service_tls_v3_grpc_certificate_provider_proto_msgTypes,
	}.Build()
	File_envoy_service_tls_v3_grpc_certificate_provider_proto = out.File
	file_envoy_service_tls_v3_grpc_certificate_provider_proto_goTypes = nil
	file_envoy_service_tls_v3_grpc_certificate_provider_proto_depIdxs = nil
}
