// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: envoy/service/tls/v3/grpc_certificate_provider.proto

package tlsv3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CertificateProviderService_FetchCertificate_FullMethodName = "/envoy.service.tls.v3.CertificateProviderService/FetchCertificate"
)

// CertificateProviderServiceClient is the client API for CertificateProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CertificateProviderServiceClient interface {
	// Fetch a certificate for a TLS connection.
	// This RPC is called during the TLS handshake when a certificate is needed.
	// The implementation should return the certificate as quickly as possible
	// to minimize handshake latency.
	FetchCertificate(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
}

type certificateProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCertificateProviderServiceClient(cc grpc.ClientConnInterface) CertificateProviderServiceClient {
	return &certificateProviderServiceClient{cc}
}

func (c *certificateProviderServiceClient) FetchCertificate(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, CertificateProviderService_FetchCertificate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertificateProviderServiceServer is the server API for CertificateProviderService service.
// All implementations should embed UnimplementedCertificateProviderServiceServer
// for forward compatibility
type CertificateProviderServiceServer interface {
	// Fetch a certificate for a TLS connection.
	// This RPC is called during the TLS handshake when a certificate is needed.
	// The implementation should return the certificate as quickly as possible
	// to minimize handshake latency.
	FetchCertificate(context.Context, *CertificateRequest) (*CertificateResponse, error)
}

// UnimplementedCertificateProviderServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCertificateProviderServiceServer struct {
}

func (UnimplementedCertificateProviderServiceServer) FetchCertificate(context.Context, *CertificateRequest) (*CertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchCertificate not implemented")
}

// UnsafeCertificateProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertificateProviderServiceServer will
// result in compilation errors.
type UnsafeCertificateProviderServiceServer interface {
	mustEmbedUnimplementedCertificateProviderServiceServer()
}

func RegisterCertificateProviderServiceServer(s grpc.ServiceRegistrar, srv CertificateProviderServiceServer) {
	s.RegisterService(&CertificateProviderService_ServiceDesc, srv)
}

func _CertificateProviderService_FetchCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateProviderServiceServer).FetchCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateProviderService_FetchCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateProviderServiceServer).FetchCertificate(ctx, req.(*CertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CertificateProviderService_ServiceDesc is the grpc.ServiceDesc for CertificateProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertificateProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "envoy.service.tls.v3.CertificateProviderService",
	HandlerType: (*CertificateProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchCertificate",
			Handler:    _CertificateProviderService_FetchCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "envoy/service/tls/v3/grpc_certificate_provider.proto",
}
